# -*- coding: utf-8 -*-
"""Fibonnaci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/137AjsBz5JfLktPc7LeMpaTjjc-iVtMCH
"""

def fibonacci_recursivo(n):
    if n <= 1:
        return n

    return fibonacci_recursivo(n - 1) + fibonacci_recursivo(n - 2)

def fibonacci_iterativo(n):
    if n <= 1:
        return n

    # Usamos dos variables para llevar la cuenta de los dos números anteriores
    a, b = 0, 1

    # Iteramos desde 2 hasta n para calcular los siguientes números
    for _ in range(2, n + 1):
        a, b = b, a + b

    return b

n = 10
print(f"Fibonacci recursivo de {n} es: {fibonacci_recursivo(n)}")
print(f"Fibonacci iterativo de {n} es: {fibonacci_iterativo(n)}")