# -*- coding: utf-8 -*-
"""Tribonnaci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SVkMCYs7JIQIcXfiHmkD6IsGBFhnJmFS
"""

def tribonacci_recursivo(n):
    if n == 0:
        return 0
    if n <= 2: # T(1) = 1, T(2) = 1
        return 1

    return tribonacci_recursivo(n - 1) + tribonacci_recursivo(n - 2) + tribonacci_recursivo(n - 3)

def tribonacci_iterativo(n):
    if n == 0:
        return 0
    if n <= 2:
        return 1

    a, b, c = 0, 1, 1

    for _ in range(3, n + 1):
        # Se calcula el siguiente término y se actualizan las variables
        a, b, c = b, c, a + b + c

    return c

def tribonacci_iterativo(n):
    """Calcula el número de Tribonacci de forma iterativa."""
    if n == 0:
        return 0
    if n <= 2:
        return 1

    # Se inicializan las variables con los 3 primeros términos
    a, b, c = 0, 1, 1

    # El bucle empieza en 3
    for _ in range(3, n + 1):
        # Se calcula el siguiente término y se actualizan las variables
        a, b, c = b, c, a + b + c

    return c

print(f"Tribonacci iterativo de {10} es: {tribonacci_iterativo(10)}")
print(f"Tribonacci recursivo de {10} es: {tribonacci_recursivo(10)}")